import type { FrictionReport, Metric, Score } from "../types.js";

const SCORE_BADGE: Record<Score, string> = {
  THIN: "**THIN**",
  SHALLOW: "**SHALLOW**",
  DEEP: "**DEEP**",
  "N/A": "N/A",
};

function fmtValue(m: Metric<number | null>, unit: string = ""): string {
  if (m.value === null) return "—";
  if (unit === "$") return `$${m.value.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;
  if (unit === "%") return `${m.value.toFixed(2)}%`;
  return m.value.toLocaleString("en-US");
}

function fmtUsd(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(2)}k`;
  return `$${n.toFixed(2)}`;
}

function shortHash(hash: string): string {
  if (hash.length < 12) return hash;
  return `${hash.slice(0, 6)}…${hash.slice(-4)}`;
}

export function renderMarkdown(report: FrictionReport): string {
  const lines: string[] = [];
  const { asset, metrics, crossChainContext, attestation } = report;
  const contractUrl = `https://mantlescan.xyz/address/${asset.contract}`;

  lines.push(`# ${asset.symbol} — Distribution Friction Report`);
  lines.push("");
  lines.push(`**Verdict: ${SCORE_BADGE[report.verdict]}**`);
  lines.push("");
  lines.push(`> ${report.verdictReason}`);
  lines.push("");
  lines.push(
    `\`${asset.name}\` ([\`${asset.contract}\`](${contractUrl})) — issued by ${asset.issuer} on ${asset.chain}.`,
  );
  lines.push(`Measured: \`${report.measuredAt}\`.`);
  lines.push("");

  lines.push("## Metrics");
  lines.push("");
  lines.push("| Metric | Score | Value | Evidence |");
  lines.push("|---|---|---|---|");
  lines.push(
    `| Mantle venue count | ${SCORE_BADGE[metrics.venueCount.score]} | ${fmtValue(metrics.venueCount)} | ${metrics.venueCount.evidence} |`,
  );
  lines.push(
    `| Top-of-book depth (USD) | ${SCORE_BADGE[metrics.depthUsd.score]} | ${fmtValue(metrics.depthUsd, "$")} | ${metrics.depthUsd.evidence} |`,
  );
  lines.push(
    `| Effective spread (bps) | ${SCORE_BADGE[metrics.spreadBps.score]} | ${fmtValue(metrics.spreadBps)} | ${metrics.spreadBps.evidence} |`,
  );
  lines.push(
    `| Reference drift (bps) | ${SCORE_BADGE[metrics.referenceDriftBps.score]} | ${fmtValue(metrics.referenceDriftBps)} | ${metrics.referenceDriftBps.evidence} |`,
  );
  lines.push(
    `| Top-10 holder concentration | ${SCORE_BADGE[metrics.concentrationPct.score]} | ${fmtValue(metrics.concentrationPct, "%")} | ${metrics.concentrationPct.evidence} |`,
  );
  lines.push("");

  if (crossChainContext && Object.keys(crossChainContext).length > 0) {
    lines.push("## Cross-chain context");
    lines.push("");
    lines.push("| Chain | TVL (USD) | Source |");
    lines.push("|---|---|---|");
    const order: Array<keyof typeof crossChainContext> = ["solana", "ethereum", "arbitrum"];
    for (const chain of order) {
      const ctx = crossChainContext[chain];
      if (!ctx) continue;
      const label = chain.charAt(0).toUpperCase() + chain.slice(1);
      lines.push(`| ${label} | ${fmtUsd(ctx.tvlUsd)} | ${ctx.source} |`);
    }
    lines.push("");
  }

  lines.push("## Onchain attestation");
  lines.push("");
  if (attestation) {
    lines.push(`- **Skill:** \`${report.skill}\` v${report.version}`);
    lines.push(`- **Agent ID:** \`${attestation.agentId}\` (Mantle mainnet, chainId ${attestation.chainId})`);
    lines.push(`- **Report hash:** \`${attestation.reportHash}\``);
    lines.push(`- **Attest tx:** [\`${shortHash(attestation.txHash)}\`](${attestation.explorerUrl})`);
  } else {
    lines.push(`- **Skill:** \`${report.skill}\` v${report.version}`);
    lines.push("- No onchain attestation in this report (run `attest-live attest <SYMBOL>` to anchor).");
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "Generated by [mantle-distribution-friction](https://github.com/captainebru84-sudo/MantleResearch). " +
      "All scores trace to re-runnable fetches; the canonical-JSON keccak256 of this report is anchored on Mantle via ERC-8004.",
  );
  lines.push("");

  return lines.join("\n");
}
